### ISSUE TITLE
Couldn't boot?

### ISSUE THREAD

**Issue by xversion1** [adi1090x/archlive#1]
I couldn't use it. I downloaded iso file and burned it to a USB. When I used etchet to flash it, etcher said this file doens't have boot but I flashed anyway. And sure enough I couldn't boot either EFI or BIOS machine. It didn't even appear in the boot options.

**Comment by grejh0t** [comment]
@adi1090x have u fixed it ?

**Comment by Darksider3** [comment]
Same problem here with literally any virtual machine software i could find(vmware, qemu, virtualbox and citrix)

**Comment by drmarwat** [comment]
same issue as being faced by others, neither etcher nor dd nor rufus will write it without warning and if forced written system will not boot it .

**Comment by adi1090x** [comment]
Project is outdated, use [this](https://github.com/adi1090x/archlinux) now.
